- operation: Add
  participant_description:
    name: MissyBot
    group: missy
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 0.2
        - 0.2