#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DIR=$SCRIPT_DIR/config

echo "Installing VNC Server for Gnome Environments"
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer -y
sudo apt install tigervnc-scraping-server -y

echo "Set a password for the VNC Server"
vncpasswd

echo "Adding startup config file for autologin"
cp $CONFIG_DIR/xstartup ~/.vnc/
sudo touch /etc/gdm3/custom.conf
sed ":%s/ubuntu/$USER/g" $CONFIG_DIR/custom.conf > /tmp/custom.conf
sudo cp /tmp/custom.conf /etc/gdm3

echo "Configuring to run VNC server on startup"
sudo touch /etc/systemd/system/x0vncserver.service
sed ":%s/ubuntu/$USER/g" $CONFIG_DIR/x0vncserver.service > /tmp/x0vncserver.service
sudo cp /tmp/x0vncserver.service /etc/systemd/system
sudo systemctl unmask x0vncserver.service
sudo systemctl enable x0vncserver.service
sudo systemctl start x0vncserver.service

echo "Set up dummy video server"
sudo apt install xserver-xorg-video-dummy-lts-xenial -y
sudo apt install xserver-xorg-video-dummy-hwe-16.04 -y
sudo cp $CONFIG_DIR/dummy-1920-1080.conf /etc/X11/xorg.conf

echo "Vncserver should be available now."
