scan_filter_chain:
- name: Range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.0
    upper_threshold: 15.0
    lower_replacement_value: -.inf
    upper_replacement_value: 14.5
- name: Box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.3
    max_x: 0.3
    min_y: -0.3
    max_y: 0.3 
    min_z: -1.0
    max_z: 1.0
- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    # Select which filter type to use.
    # 0: Range based filtering (distance between consecutive points)
    # 1: Euclidean filtering based on radius outlier search
    filter_type: 1

    # Only ranges smaller than this range are taken into account
    max_range: 2.0

    # filter_type[0] (Distance): max distance between consecutive points
    # filter_type[1] (RadiusOutlier): max distance between points
    max_range_difference: 0.05

    # filter_type[0] (Distance): Number of consecutive ranges that will be tested for max_distance
    # filter_type[1] (RadiusOutlier): Minimum number of neighbors
    filter_window: 1
