network:
  version: 2
  renderer: networkd 

  wifis:
    wlp58s0:
      dhcp4: false
      gateway4: 10.42.0.1
      access-points:
        'chart-magni-rpi49E33':
          password: 'robotseverywhere'
      addresses:
        - 10.42.0.2/24
      nameservers:
        addresses: [8.8.8.8]
