network:
  version: 2
  renderer: networkd 

  ethernets:
    usb0:
      dhcp4: false
      addresses:
        - 192.168.42.105/24 
      nameservers:
        addresses: [8.8.8.8]

  wifis:
    wlp58s0:
      dhcp4: false
      access-points:
        'chart-magni-rpi49E33':
          password: 'robotseverywhere'
      addresses:
        - 10.42.0.2/24
      nameservers:
        addresses: [8.8.8.8]
