# action.yml
name: 'build_w_docker'
description: 'build this repo with docker'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

runs:
  using: 'docker'
  image: 'Dockerfile'
